animal = "  Chanchito Feliz  "
print(animal.upper())
print(animal.lower())
print(animal.strip().capitalize())
print(animal.title())
print(animal.strip())
print(animal.lstrip())
print(animal.rstrip())
print(animal.find("ch"))
print(animal.replace("Ch", "Ho"))
print("chi" in animal)
print("chi" not in animal)
